sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        VEI4SKXCzkAH3qRCymJu4sy8FZwZyHIp5YZ3ZV6OA9GwfZtSI8zfu80UdnJnmw5KG9cEgvwFcuwIt6Kg390vrH4j3va0AyexSgH8aADZfhlTjuo19Q0Ivtclb0uQGEa4b4E6BTmXpCHkuSkdOkKtAu6F0LCYktzqUK51PFLwKuN59HkKT8vycr2QvvxEhad6eEKEmh2df+rmcANd262hjMby90o3huJiYx4t3QpqTNQywydlQhvBcjzPPHiHGVRllX0M1IzEsT6IeJeLBDP663y7BCPkpTQbngxBSY7eAZkObzUdQheUfsviapGdz2lP2kV2mNV36ZJnku4MRKgCQ0uQDKPyAnK+5YWqLrsfwIYa7U9CQ60c4ZloGe771k2U2Mde3lD+EnAa4jEettfJe7sBiLStNn28LD2p/UmJDE4SDEwBd4SIfH7bG2lqdNliZXycOiK1aSgVXDIbPhl+YcF4VY+s9EMIs62ypUARUA9HSll2rQ+WySDPYcxpMCZSEhze7b9dAiVNprMzNd+vEwJ5OAY8mbXcI5YFQv5Unj3vYxQmXodFJN9Zv//DJ2SurhJyF4pDb7LXDbrKKmVaVo7RZO0p13y6zETiTgISZD+7QQlK9+Djl1bXjFOcUTUpUpS4EcOZHGdpajnu1gsl7uBHzF+GtMqpG2gc85J8e7g=
    - secure: >-
        UolbF8Mt7mqiPaOa/1AwUk0Z891KiZhh9xVw7dwYXYzZsg6IQJ6Zead1VQJzmih713GLmmw9Ry3nWFNo4XM3F/MAspGGVfrwWU0dCy1NBipTltW63sW6SVeInbMcm6R0k1XNVsdmtC0SFXHp+NJE2EFVh7Y8TNK6O4NOkr6W8jnkzdRnIAf9z3RzR3tNdXXqLlStk/TnduN9CltZC7+k+UNHeoZIT3o4MqTPBK20ueKxLrJVuXuXw19LdDN8JnmoUeKy4U9Czdv0532R1ASoPzMi3ovHRy06UaF2+gGT5c1gq0MGHFqvlKsFWgFGclDJEds0nqrfIMg8nvD9nBmNZ3KVjdzF5ZSAR3k/ap92LlFAkXnM+bqaMPi4pcMRcie6S2zTcRsGuOeCaIO1wEzbd7DDhZc6bjMEhzSzsKc1DRFVewkNgASJxb9/YHG9SZIVLB9thb6OpMn79KwxDNRWSZmi3CRSnh4FZXFkMnB/z0VofEBcTwn2TGDHL2C6F/JvPj9TOZOFmz0iNz11DrcnC6pLHfTlp+oOW3mCIFntZ9bxUYxP6HhTeyRRdEk/yHB2bB93Abu3glRyTSnPeF3mkR1jhh56oszFjBdxaabtOA4MpNxdMPigIxGINuFZ+sI7ylOm2MnAPN8bIZx6NNEIF9E+WpbiXrLDR3X6JBTmccg=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
